services:
  brutaldon:
    #image: brutaldon:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: brutaldon
    restart: unless-stopped
    volumes:
      - "./data:/data"
    environment:
      TZ: "UTC"
      LANGUAGE_CODE: "en-us"
      SECRET_KEY: "CHANGE_ME_PLEASE"
      ALLOWED_HOSTS: "127.0.0.1,::1"
      DB_PATH: "/data/db.sqlite3"
    ports:
      - 8000:8000
